### ISSUE TITLE
Extension module isn't built

### ISSUE THREAD

**Issue by tdsmith** [conda-forge/crcmod-feedstock#12]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:
crcmod tries to build an extension module. gsutil (the Google Cloud Storage CLI client) hopes that it will be available because the extension module is much faster than the pure-python implementation, and complains if it's missing. cf. https://github.com/conda-forge/google-cloud-sdk-feedstock/issues/79

Inspecting the contents of https://anaconda.org/conda-forge/crcmod/1.7/download/linux-64/crcmod-1.7-py38h32f6830_1003.tar.bz2, it does not contain any .so files, so the compiled extension isn't being shipped in the architecture-specific versions of the package that this feedstock builds.

That means that the conda-forge flavour of crcmod can't be used to satisfy gsutil's optional dependency on a compiled crcmod.

It would be nice if the architecture-specific variants contained the extension modules.

**Comment by xylar** [comment]
@tdsmith, this feedstock has not been maintained very well and I took it on only because I needed python 3.9 support for some downstream package (not sure which).

If you have the time and expertise to add a PR to switch back to the architecture-specific builds and include the extensions you need, that would be most welcome.  If you want to add yourself as a maintainer, that would also be welcome.  Otherwise, I will try to get to this when I can.

**Comment by tdsmith** [comment]
Thanks for the response! I have some funemployment time coming up and I'll try and take a look then. (I don't want to lick the cookie, though; if someone else gets there first I won't feel deprived!)

**Comment by nehaljwani** [comment]
I've opened https://github.com/conda-forge/crcmod-feedstock/pull/13
